##
# MySQL DB dumping.
#
#
- name: Installs backup script
  template:
    src: "../templates/backup_all_databases.j2"
    dest: /usr/local/bin/backup_all_databases
    mode: 0700

- name: Ensures backup destination exists
  file:
    path: "{{ pxc_backup_destination }}"
    state: directory
    owner: root

- name: Adds backup crontab entry
  cron:
    name: Backups all databases
    job: /usr/local/bin/backup_all_databases > /var/log/pxcbackup.log 2>&1
    user: root
    day: "{{ pxc_backup_cron_day }}"
    hour: "{{ pxc_backup_cron_hour }}"
    minute: "{{ pxc_backup_cron_minute }}"
  tags: ["cron"]
