---
##
# MySQL DB dumping.
#
#  
- name: Installs backup script
  template: >
    src="../templates/backup_all_databases.j2"
    dest=/usr/local/bin/backup_all_databases
    mode=0700

- name: Ensures backup destination exists
  file: >
    path={{ pxc_backup_destination }}
    state=directory
    mode=0700
    owner=root

- name: Adds backup crontab entry
  template: >
    src="../templates/backup_all_databases.crontab.j2"
    dest=/etc/cron.d/backup_all_databases
    mode=0750
