- include: check_vars.yml tags=pxc,pxc:install

- include: pxc.yml tags=pxc,pxc:install

#- include: client.yml tags=pxc,pxc-client
- include: datadog.yml tags=pxc,pxc-client,datadog
  when: pxc_datadog_user and pxc_datadog_password and datadog_api_key is defined and datadog_api_key

- include: backup.yml tags=backup,pxc
  when: pxc_backup
